apiDir: "../change-tracking-rest-api/src/main/java"
apiPackagePath: "com.liferay.change.tracking.rest"
application:
    baseURI: "/change-tracking"
    className: "ChangeTrackingRESTApplication"
    name: "Liferay.Change.Tracking.REST"
author: "Máté Thurzó"
clientDir: "../change-tracking-rest-client/src/main/java"
testDir: "../change-tracking-rest-test/src/testIntegration/java"